version: '3.2'

services:

#-------------- WEBSERVER
  webserver:
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    - ./www:/var/www
    image: nginx:stable-alpine
    restart: unless-stopped
    logging:
      options:
        max-size: "10M"
        max-file: "10"
    ports:
    - "8080:80"